apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: example-applicationset
  namespace: argocd
spec:
  generators:
  - list:
      elements:
        - name: argo-workflows
          repoURL: https://github.com/wigo4it/DevStream.git
          revision: main
          path: argo-workflows
        - name: hello-world
          repoURL: https://github.com/wigo4it/DevStream.git
          revision: main
          path: apps/hello-world

  template:
    metadata:
      name: '{{name}}'
    spec:
      project: default
      source:
        repoURL: '{{repoURL}}'
        targetRevision: '{{revision}}'
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{name}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
